use std::collections::BTreeMap;
use std::time::Duration;

use eyre::eyre;
use log::debug;
use reqwest::Url;
use chrono::Datelike;
use rss::extension::itunes::ITunesCategory;
use rss::Channel;
use rss::{Enclosure, Item};
use urlencoding::encode;

use crate::configs::{conf, AudioCodec, Conf, ConfName};

pub fn inject_vod2pod_customizations(
    rss_body: String,
    transcode_service_url: Option<Url>,
    podcast_assets_base_url: Option<Url>,
) -> eyre::Result<String> {
    // Some providers (e.g., rss crate writers) emit an XML declaration before <rss>.
    // rss::Channel::read_from expects the document to begin with <rss>, so strip any leading BOM/XML.
    let mut normalized = rss_body.trim_start_matches('\u{feff}').trim_start().to_string();
    if normalized.starts_with("<?xml") {
        if let Some(end) = normalized.find("?>") {
            normalized = normalized[end + 2..].trim_start().to_string();
        }
    }
    if !normalized.trim_start().starts_with("<rss") {
        if let Some(pos) = normalized.find("<rss") {
            normalized = normalized[pos..].to_string();
        }
    }
    let mut injected_feed = Channel::read_from(normalized.as_bytes())?;
    injected_feed.set_generator(Some("generated by vod2pod-rss".to_string()));
    // If a provider didn't set an iTunes category, keep Apple validation-friendly defaults.
    if let Some(ref mut itunes) = injected_feed.itunes_ext {
        if itunes.categories().is_empty() {
            let mut default_category = ITunesCategory::default();
            default_category.set_text("Technology");
            itunes.set_categories(vec![default_category]);
        }
    }
    let mut namespaces = BTreeMap::new();
    namespaces.insert(
        "rss".to_string(),
        "http://www.itunes.com/dtds/podcast-1.0.dtd".to_string(),
    );
    namespaces.insert(
        "itunes".to_string(),
        "http://www.itunes.com/dtds/podcast-1.0.dtd".to_string(),
    );
    namespaces.insert(
        "content".to_string(),
        "http://purl.org/rss/1.0/modules/content/".to_string(),
    );
    namespaces.insert(
        "podcast".to_string(),
        "https://podcastindex.org/namespace/1.0".to_string(),
    );
    injected_feed.set_namespaces(namespaces);
    // Force English-only feeds.
    // Apple accepts ISO 639 codes; "en" is broadly valid.
    injected_feed.set_language("en".to_string());
    injected_feed
        .items_mut()
        .iter_mut()
        .try_for_each(|item| -> eyre::Result<_> {
            let description = get_description(item);
            item.set_description(description);
            let bitrate: u64 = conf()
                .get(ConfName::Mp3Bitrate)
                .unwrap()
                .parse()
                .expect("MP3_BITRATE must be a number");
            let generation_uuid = uuid::Uuid::new_v4().to_string();
            let codec: AudioCodec = conf().get(ConfName::AudioCodec).unwrap().into();
            let ext = format!(".{}", codec.get_extension_str());
            if let Some(mut transcode_service_url) = transcode_service_url.clone() {
                let duration_secs = &item
                    .itunes_ext()
                    .and_then(|i| Some(parse_duration(i.duration()?).ok()?.as_secs()))
                    .ok_or(eyre!(
                        "no duration found or could not parse {:?}",
                        item.itunes_ext()
                    ))?;
                transcode_service_url
                    .query_pairs_mut()
                    .append_pair("bitrate", bitrate.to_string().as_str())
                    .append_pair("uuid", generation_uuid.as_str())
                    .append_pair("duration", duration_secs.to_string().as_str())
                    .append_pair("url", item.link().ok_or(eyre!("not url found in item"))?)
                    .append_pair("ext", ext.as_str()); //this should allways be last, some players refuse to play urls not ending in .mp3

                let enclosure = Enclosure {
                    length: (bitrate * 1024 * duration_secs).to_string(),
                    url: transcode_service_url.to_string(),
                    mime_type: "audio/mpeg".to_string(),
                };

                debug!(
                    "setting enclosure to: \nlength: {}, url: {}, mime_type: {}",
                    enclosure.length, enclosure.url, enclosure.mime_type
                );
                item.set_enclosure(Some(enclosure));
            }
            Ok(())
        })?;

    let mut xml = injected_feed.to_string();
    if let Some(base) = podcast_assets_base_url {
        xml = inject_podcast_assets_tags(xml, &base);
    }
    Ok(xml)
}

fn inject_podcast_assets_tags(mut rss_xml: String, base_url: &Url) -> String {
    // NOTE: The `rss` crate doesn't natively model the Podcasting 2.0 namespace tags
    // we need (<podcast:chapters> / <podcast:transcript>), so we inject them as raw XML.

    // Ensure the root <rss> tag has the podcast namespace declaration.
    // The rss crate *usually* emits namespaces from `set_namespaces`, but this is a safe fallback.
    if !rss_xml.contains("xmlns:podcast=") {
        if let Some(pos) = rss_xml.find("<rss") {
            if let Some(end) = rss_xml[pos..].find('>') {
                let insert_at = pos + end;
                rss_xml.insert_str(
                    insert_at,
                    " xmlns:podcast=\"https://podcastindex.org/namespace/1.0\"",
                );
            }
        }
    }

    // Build base URLs for assets.
    let mut chapters_base = base_url.clone();
    chapters_base.set_path(&format!(
        "{}/yt/chapters/",
        base_url.path().trim_end_matches('/')
    ));
    let mut transcript_base = base_url.clone();
    transcript_base.set_path(&format!(
        "{}/yt/transcripts/",
        base_url.path().trim_end_matches('/')
    ));

    // Artwork endpoint (square jpeg) that fetches source art and caches in Redis.
    let mut art_base = base_url.clone();
    art_base.set_path(&format!(
        "{}/yt/art/square.jpg",
        base_url.path().trim_end_matches('/')
    ));

    // Inject show-level Apple tags if missing (channel-specific, derived from channel title).
    rss_xml = inject_channel_level_apple_tags(rss_xml);

    // Rewrite itunes:image tags to point at our artwork endpoint (Apple-safe sizing) when the
    // source image looks like a YouTube thumbnail/avatar.
    rss_xml = rewrite_itunes_image_hrefs(rss_xml, &art_base);

    // Inject per-item tags for YouTube links.
    // We keep this lightweight: derive video_id from link and always inject tags.
    // Endpoints themselves are on-demand and backed by Redis (no disk required).
    let mut out = String::with_capacity(rss_xml.len() + 1024);
    let mut cursor = 0usize;

    while let Some(item_start_rel) = rss_xml[cursor..].find("<item>") {
        let item_start = cursor + item_start_rel;
        out.push_str(&rss_xml[cursor..item_start]);

        // Find end of this item.
        let Some(item_end_rel) = rss_xml[item_start..].find("</item>") else {
            out.push_str(&rss_xml[item_start..]);
            return out;
        };
        let item_end = item_start + item_end_rel;
        let item_block = &rss_xml[item_start..item_end];

        let video_id = extract_youtube_video_id_from_item(item_block);

        if let Some(video_id) = video_id {
            let chapters_url = format!("{}{}.json", chapters_base.as_str(), video_id);
            let transcript_url = format!("{}{}.vtt", transcript_base.as_str(), video_id);

            // Apple/iTunes item-level tags we can safely default for YouTube-derived episodes.
            // Keep them channel-specific by deriving everything from the source item.
            let mut extra_item_tags = String::new();
            if !item_block.contains("<itunes:episodeType>") {
                extra_item_tags.push_str("<itunes:episodeType>full</itunes:episodeType>\n");
            }
            if !item_block.contains("<itunes:explicit>") {
                extra_item_tags.push_str("<itunes:explicit>false</itunes:explicit>\n");
            }

            out.push_str(item_block);
            out.push_str(&format!(
                "\n{}<podcast:chapters url=\"{}\" type=\"application/json+chapters\" />\n<podcast:transcript url=\"{}\" type=\"text/vtt\" />\n",
                extra_item_tags, chapters_url, transcript_url
            ));
            out.push_str("</item>");
        } else {
            out.push_str(item_block);
            out.push_str("</item>");
        }

        cursor = item_end + "</item>".len();
    }

    out.push_str(&rss_xml[cursor..]);
    out
}

fn inject_channel_level_apple_tags(mut rss_xml: String) -> String {
    // Insert missing channel-level iTunes tags before the first <item>.
    let Some(channel_start) = rss_xml.find("<channel>") else { return rss_xml; };
    let Some(first_item) = rss_xml.find("<item>") else { return rss_xml; };
    let channel_block = &rss_xml[channel_start..first_item];

    // Extract <title> / <description> for use as author/title/summary/subtitle/copyright
    let title = extract_tag_text(channel_block, "title").unwrap_or_else(|| "Podcast".to_string());
    let description = extract_tag_text(channel_block, "description").unwrap_or_default();
    let escaped_title = xml_escape(&title);
    let escaped_description = xml_escape(&description);

    // A short subtitle helps Apple search/browse; keep it within ~120 chars.
    let subtitle = if description.len() > 120 {
        description.chars().take(117).collect::<String>() + "..."
    } else {
        description.clone()
    };
    let escaped_subtitle = xml_escape(&subtitle);

    let mut insert = String::new();

    if !channel_block.contains("<itunes:author>") {
        insert.push_str(&format!("<itunes:author>{}</itunes:author>\n", escaped_title));
    }
    if !channel_block.contains("<itunes:title>") {
        insert.push_str(&format!("<itunes:title>{}</itunes:title>\n", escaped_title));
    }
    if !channel_block.contains("<itunes:summary>") && !escaped_description.is_empty() {
        insert.push_str(&format!("<itunes:summary>{}</itunes:summary>\n", escaped_description));
    }
    if !channel_block.contains("<itunes:subtitle>") && !escaped_subtitle.is_empty() {
        insert.push_str(&format!("<itunes:subtitle>{}</itunes:subtitle>\n", escaped_subtitle));
    }
    if !channel_block.contains("<itunes:type>") {
        insert.push_str("<itunes:type>episodic</itunes:type>\n");
    }
    if !channel_block.contains("<itunes:explicit>") {
        insert.push_str("<itunes:explicit>false</itunes:explicit>\n");
    }
    if !channel_block.contains("<copyright>") {
        let year = chrono::Utc::now().year();
        insert.push_str(&format!("<copyright>© {} {}</copyright>\n", year, escaped_title));
    }

    if insert.is_empty() {
        return rss_xml;
    }

    // Insert right before the first <item>
    rss_xml.insert_str(first_item, &insert);
    rss_xml
}

fn rewrite_itunes_image_hrefs(rss_xml: String, art_base: &Url) -> String {
    // Replace itunes:image href="SRC" with itunes:image href="{art_base}?src=ENC(SRC)" for
    // likely-YouTube images. This keeps the feed channel-specific (source art comes from the
    // channel/video) and Apple-compliant (square 3000x3000 jpeg).
    let mut out = String::with_capacity(rss_xml.len() + 1024);
    let mut cursor = 0usize;

    while let Some(rel) = rss_xml[cursor..].find("<itunes:image") {
        let start = cursor + rel;
        out.push_str(&rss_xml[cursor..start]);

        let Some(end_rel) = rss_xml[start..].find('>') else {
            out.push_str(&rss_xml[start..]);
            return out;
        };
        let end = start + end_rel + 1;
        let tag = &rss_xml[start..end];

        // Handle self-closing and normal tags; we only rewrite if href is present.
        if let Some(href_pos) = tag.find("href=\"") {
            let href_start = href_pos + "href=\"".len();
            let href_end = tag[href_start..].find('"').map(|x| href_start + x);

            if let Some(href_end) = href_end {
                let src = &tag[href_start..href_end];
                if looks_like_youtube_image_url(src) {
                    let rewritten = format!(
                        "{}?src={}",
                        art_base.as_str(),
                        encode(src)
                    );
                    let mut new_tag = String::with_capacity(tag.len() + 64);
                    new_tag.push_str(&tag[..href_start]);
                    new_tag.push_str(&rewritten);
                    new_tag.push_str(&tag[href_end..]);
                    out.push_str(&new_tag);
                } else {
                    out.push_str(tag);
                }
            } else {
                out.push_str(tag);
            }
        } else {
            out.push_str(tag);
        }

        cursor = end;
    }

    out.push_str(&rss_xml[cursor..]);
    out
}

fn looks_like_youtube_image_url(s: &str) -> bool {
    s.contains("ytimg.com") || s.contains("googleusercontent.com") || s.contains("img.youtube.com")
}

fn extract_tag_text(block: &str, tag: &str) -> Option<String> {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let start = block.find(&open)? + open.len();
    let end = block[start..].find(&close)? + start;
    Some(block[start..end].trim().to_string())
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

fn extract_youtube_video_id_from_item(item_xml: &str) -> Option<String> {
    let link_start = item_xml.find("<link>")? + "<link>".len();
    let link_end = item_xml[link_start..].find("</link>")? + link_start;
    let link = item_xml[link_start..link_end].trim();

    if let Some(idx) = link.find("watch?v=") {
        let id_part = &link[idx + "watch?v=".len()..];
        let id = id_part
            .split('&')
            .next()
            .unwrap_or("")
            .trim()
            .to_string();
        return (!id.is_empty()).then_some(id);
    }
    if let Some(idx) = link.find("youtu.be/") {
        let id_part = &link[idx + "youtu.be/".len()..];
        let id = id_part
            .split(['?', '&', '/'])
            .next()
            .unwrap_or("")
            .trim()
            .to_string();
        return (!id.is_empty()).then_some(id);
    }
    None
}



fn get_description(item: &Item) -> String {
    const FOOTER: &str = concat!(
        "<br><br>generated by vod2pod-rss ",
        env!("CARGO_PKG_VERSION"),
        " made by Mattia Di Eleuterio (<a href=\"https://github.com/madiele\">madiele</a>). Check out the <a href=\"https://github.com/madiele/vod2pod-rss\">GitHub repository</a>."
    );
    let description = item.description().unwrap_or_default().replace("\n", "<br>");
    let url = item.link().unwrap_or_default();
    let img = item
        .itunes_ext()
        .and_then(|i| i.image())
        .unwrap_or_default();

    let original_link = format!(
        "<br><br><a href=\"{}\"><p>link to original</p><img src=\"{}\"></a>",
        url, img
    );
    format!("{}{}{}", description, original_link, FOOTER)
}

fn parse_duration(duration_str: &str) -> Result<Duration, String> {
    let duration_parts: Vec<&str> = duration_str.split(':').rev().collect();

    let seconds = match duration_parts.first() {
        Some(sec_str) => sec_str.parse().map_err(|_| "Invalid format".to_string())?,
        None => 0,
    };

    let minutes = match duration_parts.get(1) {
        Some(min_str) => min_str.parse().map_err(|_| "Invalid format".to_string())?,
        None => 0,
    };

    let hours = match duration_parts.get(2) {
        Some(hour_str) => hour_str.parse().map_err(|_| "Invalid format".to_string())?,
        None => 0,
    };

    let duration_secs = hours * 3600 + minutes * 60 + seconds;
    Ok(Duration::from_secs(duration_secs))
}
