pub mod provider;
pub mod rumble;
pub mod twitch;
pub mod youtube;

use rss::extension::itunes::ITunesChannelExtensionBuilder;

/// Build a ChannelBuilder with sensible defaults for podcast clients.
///
/// Apple Podcasts expects standard RSS 2.0 with the iTunes namespace, and many modern
/// clients also support the Podcasting 2.0 namespace.
pub fn build_default_rss_structure() -> rss::ChannelBuilder {
    let mut feed_builder = rss::ChannelBuilder::default();

    // Common namespaces used by Apple Podcasts and most podcatchers
    let mut namespaces = std::collections::BTreeMap::new();
    namespaces.insert(
        "itunes".to_string(),
        "http://www.itunes.com/dtds/podcast-1.0.dtd".to_string(),
    );
    namespaces.insert(
        "atom".to_string(),
        "http://www.w3.org/2005/Atom".to_string(),
    );
    namespaces.insert(
        "content".to_string(),
        "http://purl.org/rss/1.0/modules/content/".to_string(),
    );
    namespaces.insert(
        "media".to_string(),
        "http://search.yahoo.com/mrss/".to_string(),
    );
    // Podcasting 2.0 namespace (chapters/transcripts and other modern extensions)
    namespaces.insert(
        "podcast".to_string(),
        "https://podcastindex.org/namespace/1.0".to_string(),
    );

    feed_builder.namespaces(namespaces);
    feed_builder.generator(Some("generated by vod2pod-rss".to_string()));

    let mut itunes_section = ITunesChannelExtensionBuilder::default();
    // Prevent indexing by third-party directories by default (can be overridden per-show later)
    itunes_section.block(Some("yes".to_string()));
    feed_builder.itunes_ext(Some(itunes_section.build()));

    feed_builder
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_feed_structure_has_namespaces() {
        let feed = build_default_rss_structure().build();
        let namespaces = feed.namespaces().clone().unwrap_or_default();

        assert_eq!(
            namespaces
                .get("itunes")
                .expect("itunes namespace missing"),
            "http://www.itunes.com/dtds/podcast-1.0.dtd"
        );
        assert_eq!(
            namespaces.get("atom").expect("atom namespace missing"),
            "http://www.w3.org/2005/Atom"
        );
        assert_eq!(
            namespaces
                .get("podcast")
                .expect("podcast namespace missing"),
            "https://podcastindex.org/namespace/1.0"
        );
    }
}
